resources: "resources.yaml"
samples: "samples.tsv"
units: "units.tsv"

modules:
  alignment: "906d25d0d4791eb5a54cba9954fddf29e27b85dd"
  compression: "v1.1.0"
  fusions: "1b0e67c"
  prealignment: "1ccc6f954b3941966d7f55251a311caed47aca1e"
  qc: "ca81558181c16766674ddc9179e27928e87cc32b"

default_container: "docker://hydragenetics/common:0.1.3"

arriba:
  assembly: ""
  blacklist: ""
  container: "docker://hydragenetics/arriba:2.3.0"
  gtf: ""

arriba_draw_fusion:
  container: "docker://hydragenetics/arriba:2.3.0"
  cytobands: ""
  gtf: ""
  protein_domains: ""

fusioncatcher:
  container: "docker://hydragenetics/fusioncatcher:1.33"
  genome_path: ""

mosdepth_bed:
  container: "docker://hydragenetics/mosdepth:0.3.2"
  design_bed: ""

multiqc:
  container: "docker://hydragenetics/multiqc:1.11"
  reports:
    RNA:
      included_unit_types:
        - "R"
      qc_files:
        - "qc/fastqc/{sample}_{type}_{flowcell}_{lane}_{barcode}_{read}_fastqc.zip"
        - "qc/mosdepth_bed/{sample}_{type}.mosdepth.summary.txt"
        - "qc/rseqc_gene_body_coverage/{sample}_{type}.geneBodyCoverage.txt"
        - "qc/rseqc_inner_distance/{sample}_{type}.inner_distance.txt"
        - "prealignment/fastp_pe/{sample}_{flowcell}_{lane}_{barcode}_{type}.json"
        - "prealignment/sortmerna/{sample}_{type}.rrna.log"

rseqc_gene_body_coverage:
  bed: ""
  container: "docker://hydragenetics/rseqc:4.0.0"

rseqc_inner_distance:
  bed: ""
  container: "docker://hydragenetics/rseqc:4.0.0"

sortmerna:
  container: "docker://hydragenetics/sortmerna:4.3.4"
  fasta:
    - ""
  index: ""

star:
  container: "docker://hydragenetics/star:2.7.10a"
  genome_index: ""

star_fusion:
  container: "docker://hydragenetics/star-fusion:1.10.1"
  genome_path: ""

trimmer_software: "fastp_pe"
