resources: "resources.yaml"
samples: "samples.tsv"
units: "units.tsv"

modules:
  alignment: "develop"
  compression: "v1.1.0"
  fusions: "develop"
  prealignment: "develop"
  qc: "develop"

default_container: "docker://hydragenetics/common:0.1.0"

arriba:
  assembly: "reference/assembly.fasta"
  blacklist: "reference/arriba_blacklist.txt"
  container: "docker://hydragenetics/arriba:2.2.1"
  gtf: "reference/assembly.gtf"

fusioncatcher:
  container: "docker://hydragenetics/fusioncatcher:1.33"
  genome_path: "reference/fusioncatcher"

mosdepth_bed:
  container: "docker://hydragenetics/mosdepth:0.3.2"
  design_bed: "reference/exomes.bed"

multiqc:
  container: "docker://hydragenetics/multiqc:1.11"
  reports:
    RNA:
      included_unit_types:
        - "R"
      qc_files:
        - "qc/fastqc/{sample}_{type}_{flowcell}_{lane}_{barcode}_{read}_fastqc.zip"
        - "qc/mosdepth_bed/{sample}_{type}.mosdepth.summary.txt"
        - "qc/rseqc_gene_body_coverage/{sample}_{type}.geneBodyCoverage.txt"
        - "qc/rseqc_inner_distance/{sample}_{type}.inner_distance.txt"
        - "prealignment/fastp_pe/{sample}_{flowcell}_{lane}_{barcode}_{type}.json"
        - "prealignment/sortmerna/{sample}_{type}.rrna.log"

rseqc_gene_body_coverage:
  bed: "reference/gene_model.bed"
  container: "docker://hydragenetics/rseqc:4.0.0"

rseqc_inner_distance:
  bed: "reference/gene_model.bed"
  container: "docker://hydragenetics/rseqc:4.0.0"

sortmerna:
  container: "docker://hydragenetics/sortmerna:4.3.4"
  fasta:
    - "reference/18s.fasta"
  index: "reference/sortmerna_idx"

star:
  container: "docker://hydragenetics/star:2.7.10a"
  genome_index: "reference/star_index"

star_fusion:
  container: "docker://hydragenetics/star-fusion:1.10.1"
  genome_path: "reference/star_fusion"

trimmer_software: "fastp_pe"
